baseURL = '/'
languageCode = 'en-us'
DefaultContentLanguage = "en"
title = "Haiyan Kong"
theme = ["hugo-theme-nostyleplease"]

[module]
  [module.hugoVersion]
    extended = true
    min      = "0.41.0"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true

  [markup.highlight]
    anchorLineNos      = false
    codeFences         = true
    guessSyntax        = false
    hl_Lines           = ''
    hl_inline          = false
    lineAnchors        = ''
    lineNoStart        = 1
    lineNos            = false
    lineNumbersInTable = true
    noClasses          = true
    noHl               = false
    style              = 'rrt'
    tabWidth           = 4

  [markup.tableOfContents]
    startLevel = 1
    endLevel   = 2
    ordered    = false

[params]
  [params.theme_config]
    appearance        = "light"
    date_format       = "2006-01-02"
    isListGroupByDate = false
    
    isShowFooter      = true # ...\layouts\index.html

    isNav = false # ...\layouts\partials\back_link.html
    #back_text = "..."
    #link1 = "demo"
    #text1 = "Demo"
